// Copyright 2025 Robin Liu <robinliu27@163.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/iam/internal/authzserver/authorization (interfaces: AuthorizationInterface)
//
// Generated by this command:
//
//	mockgen -destination mock_authorization.go -package authorization github.com/robinlg/iam/internal/authzserver/authorization AuthorizationInterface
//

// Package authorization is a generated GoMock package.
package authorization

import (
	reflect "reflect"

	ladon "github.com/ory/ladon"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizationInterface is a mock of AuthorizationInterface interface.
type MockAuthorizationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthorizationInterfaceMockRecorder is the mock recorder for MockAuthorizationInterface.
type MockAuthorizationInterfaceMockRecorder struct {
	mock *MockAuthorizationInterface
}

// NewMockAuthorizationInterface creates a new mock instance.
func NewMockAuthorizationInterface(ctrl *gomock.Controller) *MockAuthorizationInterface {
	mock := &MockAuthorizationInterface{ctrl: ctrl}
	mock.recorder = &MockAuthorizationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationInterface) EXPECT() *MockAuthorizationInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthorizationInterface) Create(arg0 *ladon.DefaultPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthorizationInterfaceMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthorizationInterface)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockAuthorizationInterface) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuthorizationInterfaceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthorizationInterface)(nil).Delete), id)
}

// DeleteCollection mocks base method.
func (m *MockAuthorizationInterface) DeleteCollection(idList []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", idList)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockAuthorizationInterfaceMockRecorder) DeleteCollection(idList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockAuthorizationInterface)(nil).DeleteCollection), idList)
}

// Get mocks base method.
func (m *MockAuthorizationInterface) Get(id string) (*ladon.DefaultPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*ladon.DefaultPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAuthorizationInterfaceMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAuthorizationInterface)(nil).Get), id)
}

// List mocks base method.
func (m *MockAuthorizationInterface) List(username string) ([]*ladon.DefaultPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", username)
	ret0, _ := ret[0].([]*ladon.DefaultPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAuthorizationInterfaceMockRecorder) List(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuthorizationInterface)(nil).List), username)
}

// LogGrantedAccessRequest mocks base method.
func (m *MockAuthorizationInterface) LogGrantedAccessRequest(request *ladon.Request, pool, deciders ladon.Policies) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogGrantedAccessRequest", request, pool, deciders)
}

// LogGrantedAccessRequest indicates an expected call of LogGrantedAccessRequest.
func (mr *MockAuthorizationInterfaceMockRecorder) LogGrantedAccessRequest(request, pool, deciders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogGrantedAccessRequest", reflect.TypeOf((*MockAuthorizationInterface)(nil).LogGrantedAccessRequest), request, pool, deciders)
}

// LogRejectedAccessRequest mocks base method.
func (m *MockAuthorizationInterface) LogRejectedAccessRequest(request *ladon.Request, pool, deciders ladon.Policies) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRejectedAccessRequest", request, pool, deciders)
}

// LogRejectedAccessRequest indicates an expected call of LogRejectedAccessRequest.
func (mr *MockAuthorizationInterfaceMockRecorder) LogRejectedAccessRequest(request, pool, deciders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRejectedAccessRequest", reflect.TypeOf((*MockAuthorizationInterface)(nil).LogRejectedAccessRequest), request, pool, deciders)
}

// Update mocks base method.
func (m *MockAuthorizationInterface) Update(arg0 *ladon.DefaultPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAuthorizationInterfaceMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthorizationInterface)(nil).Update), arg0)
}
