// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robinlg/iam/internal/apiserver/service/v1 (interfaces: Service,UserSrv,SecretSrv,PolicySrv)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/robinlg/iam/internal/apiserver/service/v1 -destination mock_service.go -package v1 github.com/robinlg/iam/internal/apiserver/service/v1 Service,UserSrv,SecretSrv,PolicySrv
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	v1 "github.com/robinlg/iamapi/apiserver/v1"
	v10 "github.com/robinlg/iamlib/pkg/meta/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Policies mocks base method.
func (m *MockService) Policies() PolicySrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Policies")
	ret0, _ := ret[0].(PolicySrv)
	return ret0
}

// Policies indicates an expected call of Policies.
func (mr *MockServiceMockRecorder) Policies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Policies", reflect.TypeOf((*MockService)(nil).Policies))
}

// Secrets mocks base method.
func (m *MockService) Secrets() SecretSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secrets")
	ret0, _ := ret[0].(SecretSrv)
	return ret0
}

// Secrets indicates an expected call of Secrets.
func (mr *MockServiceMockRecorder) Secrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secrets", reflect.TypeOf((*MockService)(nil).Secrets))
}

// Users mocks base method.
func (m *MockService) Users() UserSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(UserSrv)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockServiceMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockService)(nil).Users))
}

// MockUserSrv is a mock of UserSrv interface.
type MockUserSrv struct {
	ctrl     *gomock.Controller
	recorder *MockUserSrvMockRecorder
	isgomock struct{}
}

// MockUserSrvMockRecorder is the mock recorder for MockUserSrv.
type MockUserSrvMockRecorder struct {
	mock *MockUserSrv
}

// NewMockUserSrv creates a new mock instance.
func NewMockUserSrv(ctrl *gomock.Controller) *MockUserSrv {
	mock := &MockUserSrv{ctrl: ctrl}
	mock.recorder = &MockUserSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSrv) EXPECT() *MockUserSrvMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUserSrv) ChangePassword(ctx context.Context, user *v1.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserSrvMockRecorder) ChangePassword(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserSrv)(nil).ChangePassword), ctx, user)
}

// Create mocks base method.
func (m *MockUserSrv) Create(ctx context.Context, user *v1.User, opts v10.CreateOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserSrvMockRecorder) Create(ctx, user, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserSrv)(nil).Create), ctx, user, opts)
}

// Delete mocks base method.
func (m *MockUserSrv) Delete(ctx context.Context, username string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, username, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserSrvMockRecorder) Delete(ctx, username, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserSrv)(nil).Delete), ctx, username, opts)
}

// DeleteCollection mocks base method.
func (m *MockUserSrv) DeleteCollection(ctx context.Context, usernames []string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", ctx, usernames, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockUserSrvMockRecorder) DeleteCollection(ctx, usernames, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockUserSrv)(nil).DeleteCollection), ctx, usernames, opts)
}

// Get mocks base method.
func (m *MockUserSrv) Get(ctx context.Context, username string, opts v10.GetOptions) (*v1.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, username, opts)
	ret0, _ := ret[0].(*v1.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserSrvMockRecorder) Get(ctx, username, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserSrv)(nil).Get), ctx, username, opts)
}

// List mocks base method.
func (m *MockUserSrv) List(ctx context.Context, opts v10.ListOptions) (*v1.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(*v1.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserSrvMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserSrv)(nil).List), ctx, opts)
}

// ListWithBadPerformance mocks base method.
func (m *MockUserSrv) ListWithBadPerformance(ctx context.Context, opts v10.ListOptions) (*v1.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithBadPerformance", ctx, opts)
	ret0, _ := ret[0].(*v1.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithBadPerformance indicates an expected call of ListWithBadPerformance.
func (mr *MockUserSrvMockRecorder) ListWithBadPerformance(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithBadPerformance", reflect.TypeOf((*MockUserSrv)(nil).ListWithBadPerformance), ctx, opts)
}

// Update mocks base method.
func (m *MockUserSrv) Update(ctx context.Context, user *v1.User, opts v10.UpdateOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserSrvMockRecorder) Update(ctx, user, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserSrv)(nil).Update), ctx, user, opts)
}

// MockSecretSrv is a mock of SecretSrv interface.
type MockSecretSrv struct {
	ctrl     *gomock.Controller
	recorder *MockSecretSrvMockRecorder
	isgomock struct{}
}

// MockSecretSrvMockRecorder is the mock recorder for MockSecretSrv.
type MockSecretSrvMockRecorder struct {
	mock *MockSecretSrv
}

// NewMockSecretSrv creates a new mock instance.
func NewMockSecretSrv(ctrl *gomock.Controller) *MockSecretSrv {
	mock := &MockSecretSrv{ctrl: ctrl}
	mock.recorder = &MockSecretSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretSrv) EXPECT() *MockSecretSrvMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecretSrv) Create(ctx context.Context, secret *v1.Secret, opts v10.CreateOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, secret, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecretSrvMockRecorder) Create(ctx, secret, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecretSrv)(nil).Create), ctx, secret, opts)
}

// Delete mocks base method.
func (m *MockSecretSrv) Delete(ctx context.Context, username, secretID string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, username, secretID, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecretSrvMockRecorder) Delete(ctx, username, secretID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSecretSrv)(nil).Delete), ctx, username, secretID, opts)
}

// DeleteCollection mocks base method.
func (m *MockSecretSrv) DeleteCollection(ctx context.Context, username string, secretIDs []string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", ctx, username, secretIDs, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockSecretSrvMockRecorder) DeleteCollection(ctx, username, secretIDs, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockSecretSrv)(nil).DeleteCollection), ctx, username, secretIDs, opts)
}

// Get mocks base method.
func (m *MockSecretSrv) Get(ctx context.Context, username, secretID string, opts v10.GetOptions) (*v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, username, secretID, opts)
	ret0, _ := ret[0].(*v1.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecretSrvMockRecorder) Get(ctx, username, secretID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSecretSrv)(nil).Get), ctx, username, secretID, opts)
}

// List mocks base method.
func (m *MockSecretSrv) List(ctx context.Context, username string, opts v10.ListOptions) (*v1.SecretList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, username, opts)
	ret0, _ := ret[0].(*v1.SecretList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecretSrvMockRecorder) List(ctx, username, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecretSrv)(nil).List), ctx, username, opts)
}

// Update mocks base method.
func (m *MockSecretSrv) Update(ctx context.Context, secret *v1.Secret, opts v10.UpdateOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, secret, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSecretSrvMockRecorder) Update(ctx, secret, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSecretSrv)(nil).Update), ctx, secret, opts)
}

// MockPolicySrv is a mock of PolicySrv interface.
type MockPolicySrv struct {
	ctrl     *gomock.Controller
	recorder *MockPolicySrvMockRecorder
	isgomock struct{}
}

// MockPolicySrvMockRecorder is the mock recorder for MockPolicySrv.
type MockPolicySrvMockRecorder struct {
	mock *MockPolicySrv
}

// NewMockPolicySrv creates a new mock instance.
func NewMockPolicySrv(ctrl *gomock.Controller) *MockPolicySrv {
	mock := &MockPolicySrv{ctrl: ctrl}
	mock.recorder = &MockPolicySrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicySrv) EXPECT() *MockPolicySrvMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPolicySrv) Create(ctx context.Context, policy *v1.Policy, opts v10.CreateOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, policy, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPolicySrvMockRecorder) Create(ctx, policy, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPolicySrv)(nil).Create), ctx, policy, opts)
}

// Delete mocks base method.
func (m *MockPolicySrv) Delete(ctx context.Context, username, name string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, username, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPolicySrvMockRecorder) Delete(ctx, username, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPolicySrv)(nil).Delete), ctx, username, name, opts)
}

// DeleteCollection mocks base method.
func (m *MockPolicySrv) DeleteCollection(ctx context.Context, username string, names []string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", ctx, username, names, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockPolicySrvMockRecorder) DeleteCollection(ctx, username, names, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockPolicySrv)(nil).DeleteCollection), ctx, username, names, opts)
}

// Get mocks base method.
func (m *MockPolicySrv) Get(ctx context.Context, username, name string, opts v10.GetOptions) (*v1.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, username, name, opts)
	ret0, _ := ret[0].(*v1.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPolicySrvMockRecorder) Get(ctx, username, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPolicySrv)(nil).Get), ctx, username, name, opts)
}

// List mocks base method.
func (m *MockPolicySrv) List(ctx context.Context, username string, opts v10.ListOptions) (*v1.PolicyList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, username, opts)
	ret0, _ := ret[0].(*v1.PolicyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPolicySrvMockRecorder) List(ctx, username, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPolicySrv)(nil).List), ctx, username, opts)
}

// Update mocks base method.
func (m *MockPolicySrv) Update(ctx context.Context, policy *v1.Policy, opts v10.UpdateOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, policy, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPolicySrvMockRecorder) Update(ctx, policy, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPolicySrv)(nil).Update), ctx, policy, opts)
}
